/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201907221221.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V1_PROJ_TESTCODE_COMMON_TYPES_DBUS_DEPLOYMENT_HPP_
#define V1_PROJ_TESTCODE_COMMON_TYPES_DBUS_DEPLOYMENT_HPP_

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/DBus/DBusDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace proj {
namespace testcode {
namespace CommonTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StringDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::DBus::IntegerDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> a1StructDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::IntegerDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> a2StructDeployment_t;


// typecollection-specific deployments

} // namespace CommonTypes_
} // namespace testcode
} // namespace proj
} // namespace v1

#endif // V1_PROJ_TESTCODE_COMMON_TYPES_DBUS_DEPLOYMENT_HPP_
