/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201907221047.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_PROJ_TESTCODE_Test__Code_PROXY_BASE_HPP_
#define V1_PROJ_TESTCODE_Test__Code_PROXY_BASE_HPP_

#include <v1/proj/testcode/Test_Code.hpp>


#include <v1/proj/testcode/CommonTypes.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace proj {
namespace testcode {

class Test_CodeProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableAttribute< int32_t> SpeedValueAttribute;
    typedef CommonAPI::ObservableAttribute< int32_t> RpmValueAttribute;
    typedef CommonAPI::ObservableAttribute< ::v1::proj::testcode::CommonTypes::a2Struct> A2Attribute;

    typedef std::function<void(const CommonAPI::CallStatus&, const int32_t&)> Num_exAsyncCallback;

    virtual SpeedValueAttribute& getSpeedValueAttribute() = 0;
    virtual RpmValueAttribute& getRpmValueAttribute() = 0;
    virtual A2Attribute& getA2Attribute() = 0;


    virtual void num_ex(const int32_t &_input_num, CommonAPI::CallStatus &_internalCallStatus, int32_t &_output_num, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> num_exAsync(const int32_t &_input_num, Num_exAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
};

} // namespace testcode
} // namespace proj
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_PROJ_TESTCODE_Test__Code_PROXY_BASE_HPP_
