/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201907221047.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_PROJ_TESTCODE_Test__Code_PROXY_BASE_HPP_
#define V1_PROJ_TESTCODE_Test__Code_PROXY_BASE_HPP_

#include <v1/proj/testcode/Test_Code.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif


#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Proxy.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace proj {
namespace testcode {

class Test_CodeProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableAttribute< int32_t> SpeedValueAttribute;
    typedef CommonAPI::ObservableAttribute< int32_t> RpmValueAttribute;


    virtual SpeedValueAttribute& getSpeedValueAttribute() = 0;
    virtual RpmValueAttribute& getRpmValueAttribute() = 0;


};

} // namespace testcode
} // namespace proj
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_PROJ_TESTCODE_Test__Code_PROXY_BASE_HPP_
