/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201907221221.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_PROJ_TESTCODE_Test__Code_DBUS_STUB_ADAPTER_HPP_
#define V1_PROJ_TESTCODE_Test__Code_DBUS_STUB_ADAPTER_HPP_

#include <v1/proj/testcode/Test_CodeStub.hpp>
#include "v1/proj/testcode/Test_CodeDBusDeployment.hpp"
#include <v1/proj/testcode/CommonTypesDBusDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace proj {
namespace testcode {

template <typename _Stub = ::v1::proj::testcode::Test_CodeStub, typename... _Stubs>
class Test_CodeDBusStubAdapterInternal
    : public virtual Test_CodeStubAdapter,
      public CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...>
     {
public:
    typedef CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...> Test_CodeDBusStubAdapterHelper;

    ~Test_CodeDBusStubAdapterInternal() {
        deactivateManagedInstances();
        Test_CodeDBusStubAdapterHelper::deinit();
    }

    virtual bool hasFreedesktopProperties() {
        return false;
    }

    inline static const char* getInterface() {
        return Test_Code::getInterface();
    }

    void fireSpeedValueAttributeChanged(const int32_t& value);

    void fireRpmValueAttributeChanged(const int32_t& value);

    void fireA2AttributeChanged(const ::v1::proj::testcode::CommonTypes::a2Struct& value);

    void deactivateManagedInstances() {
    }

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::proj::testcode::Test_CodeStub,
        CommonAPI::Version
        > getTest_CodeInterfaceVersionStubDispatcher;

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
            ::v1::proj::testcode::Test_CodeStub,
            int32_t,
            CommonAPI::DBus::IntegerDeployment
            > getSpeedValueAttributeStubDispatcher;
    static CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
            ::v1::proj::testcode::Test_CodeStub,
            int32_t,
            CommonAPI::DBus::IntegerDeployment
            > setSpeedValueAttributeStubDispatcher;

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
            ::v1::proj::testcode::Test_CodeStub,
            int32_t,
            CommonAPI::DBus::IntegerDeployment
            > getRpmValueAttributeStubDispatcher;
    static CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
            ::v1::proj::testcode::Test_CodeStub,
            int32_t,
            CommonAPI::DBus::IntegerDeployment
            > setRpmValueAttributeStubDispatcher;

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
            ::v1::proj::testcode::Test_CodeStub,
            ::v1::proj::testcode::CommonTypes::a2Struct,
            ::v1::proj::testcode::CommonTypes_::a2StructDeployment_t
            > getA2AttributeStubDispatcher;
    static CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
            ::v1::proj::testcode::Test_CodeStub,
            ::v1::proj::testcode::CommonTypes::a2Struct,
            ::v1::proj::testcode::CommonTypes_::a2StructDeployment_t
            > setA2AttributeStubDispatcher;

    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::proj::testcode::Test_CodeStub,
        std::tuple< int32_t>,
        std::tuple< int32_t>,
        std::tuple< CommonAPI::DBus::IntegerDeployment>,
        std::tuple< CommonAPI::DBus::IntegerDeployment>
    
        > num_exStubDispatcher;

    Test_CodeDBusStubAdapterInternal(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
    : CommonAPI::DBus::DBusStubAdapter(_address, _connection,false),
      Test_CodeDBusStubAdapterHelper(_address, _connection, false, _stub) {
        Test_CodeDBusStubAdapterHelper::addStubDispatcher({ "getSpeedValueAttribute", "" }, &getSpeedValueAttributeStubDispatcher);
        Test_CodeDBusStubAdapterHelper::addStubDispatcher({ "setSpeedValueAttribute", "i" }, &setSpeedValueAttributeStubDispatcher);
        Test_CodeDBusStubAdapterHelper::addStubDispatcher({ "getRpmValueAttribute", "" }, &getRpmValueAttributeStubDispatcher);
        Test_CodeDBusStubAdapterHelper::addStubDispatcher({ "setRpmValueAttribute", "i" }, &setRpmValueAttributeStubDispatcher);
        Test_CodeDBusStubAdapterHelper::addStubDispatcher({ "getA2Attribute", "" }, &getA2AttributeStubDispatcher);
        Test_CodeDBusStubAdapterHelper::addStubDispatcher({ "setA2Attribute", "(ibd)" }, &setA2AttributeStubDispatcher);
        Test_CodeDBusStubAdapterHelper::addStubDispatcher({ "num_ex", "i" }, &num_exStubDispatcher);
        Test_CodeDBusStubAdapterHelper::addStubDispatcher({ "getInterfaceVersion", "" }, &getTest_CodeInterfaceVersionStubDispatcher);
    }

protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const {
        static const std::string introspectionData =
            "<method name=\"getInterfaceVersion\">\n"
                "<arg name=\"value\" type=\"uu\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"getSpeedValueAttribute\">\n"
            "<arg name=\"value\" type=\"i\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"setSpeedValueAttribute\">\n"
            "<arg name=\"requestedValue\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"setValue\" type=\"i\" direction=\"out\" />\n"
            "</method>\n"
            "<signal name=\"onSpeedValueAttributeChanged\">\n"
            "<arg name=\"changedValue\" type=\"i\" />\n"
            "</signal>\n"
            "<method name=\"getRpmValueAttribute\">\n"
            "<arg name=\"value\" type=\"i\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"setRpmValueAttribute\">\n"
            "<arg name=\"requestedValue\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"setValue\" type=\"i\" direction=\"out\" />\n"
            "</method>\n"
            "<signal name=\"onRpmValueAttributeChanged\">\n"
            "<arg name=\"changedValue\" type=\"i\" />\n"
            "</signal>\n"
            "<method name=\"getA2Attribute\">\n"
            "<arg name=\"value\" type=\"(ibd)\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"setA2Attribute\">\n"
            "<arg name=\"requestedValue\" type=\"(ibd)\" direction=\"in\" />\n"
            "<arg name=\"setValue\" type=\"(ibd)\" direction=\"out\" />\n"
            "</method>\n"
            "<signal name=\"onA2AttributeChanged\">\n"
            "<arg name=\"changedValue\" type=\"(ibd)\" />\n"
            "</signal>\n"
            "<method name=\"num_ex\">\n"
            "<arg name=\"_input_num\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"_output_num\" type=\"i\" direction=\"out\" />\n"
            "</method>\n"
            ;
        return introspectionData.c_str();
    }

private:
};


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
    ::v1::proj::testcode::Test_CodeStub,
    CommonAPI::Version
    > Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::getTest_CodeInterfaceVersionStubDispatcher(&Test_CodeStub::lockInterfaceVersionAttribute, &Test_CodeStub::getInterfaceVersion, "uu");

template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::proj::testcode::Test_CodeStub,
        int32_t,
        CommonAPI::DBus::IntegerDeployment
        > Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::getSpeedValueAttributeStubDispatcher(
            &::v1::proj::testcode::Test_CodeStub::lockSpeedValueAttribute,
            &::v1::proj::testcode::Test_CodeStub::getSpeedValueAttribute
            , "i"
            );
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
        ::v1::proj::testcode::Test_CodeStub,
        int32_t,
        CommonAPI::DBus::IntegerDeployment
        > Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::setSpeedValueAttributeStubDispatcher(
                &::v1::proj::testcode::Test_CodeStub::lockSpeedValueAttribute,
                &::v1::proj::testcode::Test_CodeStub::getSpeedValueAttribute,
                &Test_CodeStubRemoteEvent::onRemoteSetSpeedValueAttribute,
                &Test_CodeStubRemoteEvent::onRemoteSpeedValueAttributeChanged
                ,&Test_CodeStubAdapter::fireSpeedValueAttributeChanged
                ,"i"
                );

template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::proj::testcode::Test_CodeStub,
        int32_t,
        CommonAPI::DBus::IntegerDeployment
        > Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::getRpmValueAttributeStubDispatcher(
            &::v1::proj::testcode::Test_CodeStub::lockRpmValueAttribute,
            &::v1::proj::testcode::Test_CodeStub::getRpmValueAttribute
            , "i"
            );
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
        ::v1::proj::testcode::Test_CodeStub,
        int32_t,
        CommonAPI::DBus::IntegerDeployment
        > Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::setRpmValueAttributeStubDispatcher(
                &::v1::proj::testcode::Test_CodeStub::lockRpmValueAttribute,
                &::v1::proj::testcode::Test_CodeStub::getRpmValueAttribute,
                &Test_CodeStubRemoteEvent::onRemoteSetRpmValueAttribute,
                &Test_CodeStubRemoteEvent::onRemoteRpmValueAttributeChanged
                ,&Test_CodeStubAdapter::fireRpmValueAttributeChanged
                ,"i"
                );

template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::proj::testcode::Test_CodeStub,
        ::v1::proj::testcode::CommonTypes::a2Struct,
        ::v1::proj::testcode::CommonTypes_::a2StructDeployment_t
        > Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::getA2AttributeStubDispatcher(
            &::v1::proj::testcode::Test_CodeStub::lockA2Attribute,
            &::v1::proj::testcode::Test_CodeStub::getA2Attribute
            , "(ibd)"
            );
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
        ::v1::proj::testcode::Test_CodeStub,
        ::v1::proj::testcode::CommonTypes::a2Struct,
        ::v1::proj::testcode::CommonTypes_::a2StructDeployment_t
        > Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::setA2AttributeStubDispatcher(
                &::v1::proj::testcode::Test_CodeStub::lockA2Attribute,
                &::v1::proj::testcode::Test_CodeStub::getA2Attribute,
                &Test_CodeStubRemoteEvent::onRemoteSetA2Attribute,
                &Test_CodeStubRemoteEvent::onRemoteA2AttributeChanged
                ,&Test_CodeStubAdapter::fireA2AttributeChanged
                ,"(ibd)"
                );


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::proj::testcode::Test_CodeStub,
    std::tuple< int32_t>,
    std::tuple< int32_t>,
    std::tuple< CommonAPI::DBus::IntegerDeployment>,
    std::tuple< CommonAPI::DBus::IntegerDeployment>

    > Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::num_exStubDispatcher(
    &Test_CodeStub::num_ex, "i",
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)));

template <typename _Stub, typename... _Stubs>
void Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::fireSpeedValueAttributeChanged(const int32_t& value) {
    CommonAPI::Deployable< int32_t, CommonAPI::DBus::IntegerDeployment> deployedValue(value, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<
    CommonAPI::Deployable<
        int32_t,
        CommonAPI::DBus::IntegerDeployment
    >
    >>
        ::sendSignal(
            *this,
            "onSpeedValueAttributeChanged",
            "i",
            deployedValue
    
    );
}

template <typename _Stub, typename... _Stubs>
void Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::fireRpmValueAttributeChanged(const int32_t& value) {
    CommonAPI::Deployable< int32_t, CommonAPI::DBus::IntegerDeployment> deployedValue(value, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<
    CommonAPI::Deployable<
        int32_t,
        CommonAPI::DBus::IntegerDeployment
    >
    >>
        ::sendSignal(
            *this,
            "onRpmValueAttributeChanged",
            "i",
            deployedValue
    
    );
}

template <typename _Stub, typename... _Stubs>
void Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>::fireA2AttributeChanged(const ::v1::proj::testcode::CommonTypes::a2Struct& value) {
    CommonAPI::Deployable< ::v1::proj::testcode::CommonTypes::a2Struct, ::v1::proj::testcode::CommonTypes_::a2StructDeployment_t> deployedValue(value, static_cast< ::v1::proj::testcode::CommonTypes_::a2StructDeployment_t* >(nullptr));
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<
    CommonAPI::Deployable<
        ::v1::proj::testcode::CommonTypes::a2Struct,
        ::v1::proj::testcode::CommonTypes_::a2StructDeployment_t
    >
    >>
        ::sendSignal(
            *this,
            "onA2AttributeChanged",
            "(ibd)",
            deployedValue
    
    );
}


template <typename _Stub = ::v1::proj::testcode::Test_CodeStub, typename... _Stubs>
class Test_CodeDBusStubAdapter
    : public Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< Test_CodeDBusStubAdapter<_Stub, _Stubs...>> {
public:
    Test_CodeDBusStubAdapter(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
        : CommonAPI::DBus::DBusStubAdapter(
            _address,
            _connection,
            false),
          Test_CodeDBusStubAdapterInternal<_Stub, _Stubs...>(
            _address,
            _connection,
            _stub) {
    }
};

} // namespace testcode
} // namespace proj
} // namespace v1

#endif // V1_PROJ_TESTCODE_Test__Code_DBUS_STUB_ADAPTER_HPP_
